#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: user
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    open-in-view: false

spring:
  cloud:
    vault:
      token:
      scheme: http
      host: localhost
      port: 8200