axon:
  axonserver:
    servers: localhost:8124
  serializer:
    events: jackson
    messages: jackson
    general: xstream

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fastcampus_pay?useSSL=false&allowPublicKeyRetrieval=true
    username: mysqluser
    password: mysqlpw
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
  batch:
    jdbc:
      initialize-schema: always

kafka:
  clusters:
    bootstrap-servers: localhost:9092

logging:
  topic: fastcampus.logging.out.stdout

service:
  membership:
    url: http://localhost:8081
  banking:
    url: http://localhost:8082
  money:
    url: http://localhost:8083
